dealership/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dealership_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    
]

dealership_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('cars/', views.car_index, name='car-index'),
    path('cars/<int:car_id>', views.car_detail, name='car-detail'),
    path('cars/create/', views.CarCreate.as_view(), name='car-create'),
    path('car/<int:pk>/update/', views.CarUpdate.as_view(), name='car-update'),
    path('car/<int:pk>/delete/', views.CarDelete.as_view(), name='car-delete'),
    path('cats/<int:car_id>/add-service/', views.add_service, name='add-service'),
    path('mods/create/', views.ModCreate.as_view(), name='mod-create'),
    path('mods/<int:pk>/', views.ModDetail.as_view(), name='mod-detail'),
    path('mods/', views.ModList.as_view(), name='mod-index'),
    path('mods/<int:pk>/update/', views.ModUpdate.as_view(), name='mod-update'),
    path('mods/<int:pk>/delete/', views.ModDelete.as_view(), name='mod-delete'),
    path('cars/<int:car_id>/associate-mod/<int:mod_id>/', views.associate_mod, name='associate-mod'),
    path('cars/<int:car_id>/remove-mod/<int:mod_id>/', views.remove_mod, name='remove-mod'),
    path('accounts/signup/', views.signup, name='signup'),

]

dealership_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

SERVICE = (
    ('SM', 'Standard Maintenance'),
    ('WA', 'Wash'),
    ('BA', 'Battery'),
    ('AC', 'Air Conditioning'),
    ('WW', 'Windshield Wieprs'),
    ('TP', 'Tire Pressure'),
    ('FS', 'Full Service'),
    ('AL', 'Wheel Alignment'),
    ('BI', 'Brake Service'),
    ('TR', 'Tire Rotation'),
    ('OC', 'Oil Change'),
    ('CC', 'Coolant Service'),
    ('SS', 'Suspension Service'),
    ('PS', 'Power Steering'),
    ('TS', 'Transmission Service'),
    ('ES', 'Engine Service'),
    
)
class Mod(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('mod-detail', kwargs={'pk':self.id})
    class Meta:
        ordering = ['name']


class Car(models.Model):

    TRANS_TYPES = [
        ("M", "Manual"),
        ("A", "Automatic"),
        ("C", "CVT")
    ]
    DRIVETRAIN = {
        '4' : 'Four Wheel Drive',
        'A' : "All Wheel Drive",
        'F' : "Front Wheel Drive",
        'R' : "Rear Wheel Drive"
    }
    
    year = models.IntegerField()
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=100)
    price = models.IntegerField()
    trans = models.CharField('Transmission', max_length=1, choices=TRANS_TYPES)
    epa = models.IntegerField('MPG')
    drivetrain = models.CharField(max_length=1, choices=DRIVETRAIN)
    engine = models.CharField(max_length=250)
    intColor = models.CharField('Interior Color', max_length=25)
    extColor = models.CharField('Exterior Color', max_length=25)
    vin = models.CharField('VIN', max_length=25)
    description = models.TextField()

    mods = models.ManyToManyField(Mod)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.vin
    
    def get_absolute_url(self):
        return reverse('car-detail', kwargs={'car_id': self.id})

class Service(models.Model):
    date = models.DateField('Service date')
    sType = models.CharField('Service Type', max_length=2, choices=SERVICE, default=SERVICE[0][0])

    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_sType_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

dealership_app/forms.py
from django import forms
from .models import Service

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['date', 'sType']
        widgets = {
                        'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

dealership_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Car, Mod
from .forms import ServiceForm
from django.contrib.auth.views import LoginView

class Home(LoginView):
    template_name = 'home.html'

def about(request):
    return render(request, 'about.html')

@login_required
def car_index(request):
    cars = Car.objects.filter(user=request.user)
    return render(request, 'cars/index.html', {'cars':cars})

@login_required
def car_detail(request, car_id):
    car = Car.objects.get(id=car_id)
    mods_car_doesnt_have = Mod.objects.exclude(id__in = car.mods.all().values_list('id'))
    service_form = ServiceForm()
    return render(request, 'cars/detail.html', {
        'car':car, 
        'service_form': service_form, 
        'mods': mods_car_doesnt_have
    })

@login_required
def add_service(request, car_id):
    form = ServiceForm(request.POST)
    if form.is_valid():
        new_service = form.save(commit=False)
        new_service.car_id = car_id
        new_service.save()
    return redirect('car-detail', car_id=car_id)

@login_required
def associate_mod(request, car_id, mod_id):
    Car.objects.get(id=car_id).mods.add(mod_id)
    return redirect('car-detail', car_id=car_id)

@login_required
def remove_mod(request, car_id, mod_id):
    car = Car.objects.get(id=car_id)
    car.mods.remove(mod_id)
    return redirect('car-detail', car_id=car.id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('car-index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

class CarCreate(LoginRequiredMixin, CreateView):
    model = Car
    fields = [
        'year',
        'make',
        'model',
        'price',
        'trans',
        'epa',
        'drivetrain',
        'engine',
        'intColor',
        'extColor',
        'vin',
        'description'
    ]
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CarUpdate(LoginRequiredMixin, UpdateView):
    model = Car
    fields = [
        'year',
        'make',
        'model',
        'price',
        'trans',
        'epa',
        'drivetrain',
        'engine',
        'intColor',
        'extColor',
        'vin',
        'description'
    ]

class CarDelete(LoginRequiredMixin, DeleteView):
    model = Car
    success_url = '/cars/'

class ModCreate(LoginRequiredMixin, CreateView):
    model = Mod
    fields = ['name', 'description']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class ModList(LoginRequiredMixin, ListView):
    model = Mod

class ModDetail(LoginRequiredMixin, DetailView):
    model = Mod

class ModUpdate(LoginRequiredMixin, UpdateView):
    model = Mod
    fields = ['name','description']

class ModDelete(LoginRequiredMixin, DeleteView):
    model = Mod
    success_url = '/mods/'

    def test_func(self):
        mod = self.get_object()
        return self.request.user == mod.created_by

dealership_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About the Developer!</h1>
<hr />
<h2 class="page-content">
  <ul>
    <a href="https://www.linkedin.com/in/ariel-w-winters/"><li>Ari Winters LinkedIn</li></a>
    
    <a href="https://arielwwinters.wixsite.com/arielwinters"><li>Ari Winters Website</li></a>

    <a href="https://github.com/arielwin"><li>Ari Winters GitHub</li></a>
  </ul>
</h2>
{% endblock %}

dealership_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" type="image/png" href="" />
  <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  <link rel="shortcut icon" type='image/png' href="{%static 'images/car-svg.svg'%}" />
  <title>Garage Keeper</title>
  {% block head %}
  {% endblock %}
</head>

<body>
  <header>
    <div class="header-logo-container">
      <a href="/">
        <img src="{% static 'images/car-svg.svg' %}" alt="GG's Logo" style="max-width: 50px; height: 100%;" />
      </a>
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'car-index' %}">All Cars</a></li>
        <li><a href="{% url 'mod-index' %}">All Mods</a></li>
        <li><a href="{% url 'car-create' %}">Add a Car</a></li>
        <li><a href="{% url 'mod-create' %}">Add a Mod</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li>
          <form id="logout-form" method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit">Log out</button>
          </form>
        </li>
        {% else %}
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'home' %}">Login</a></li>
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}

      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>

</html>

dealership_app/templates/cars/detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/cars/car-detail.css' %}" />
{% endblock %}
{% block content %}
<section class="car-container">
  <div class="car-details">
    <div class="car-img">
      <img src="" alt="{{ car.year }} {{car.make}} {{car.model}}" />
    </div>
    <div class="car-container">
      <h2>Details about your {{ car.year }} {{ car.make}} {{car.model}}: </h2>
      <h2>This is a(n) {{ car.get_trans_display }} transmission vehicle mated to a(n) 
        {{ car.get_drivetrain_display }} drivetrain powered by a {{ car.engine }}. The exterior color
        is {{ car.extColor }} and the interior color is {{ car.intColor }}. Your most recent
        gas milage was reported as {{ car.epa }} MPG.</h2>
      <h3>Your short description: {{ car.description }}</h3>
    </div >


    <div class="car-actions">
      <a href="{% url 'car-update' car.id %}" class="btn warn">Edit</a>
      <a href="{% url 'car-delete' car.id %}" class="btn danger">Delete</a>
    </div>
    </div></div>
  </div>
</section>

<div class="maint-mods-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Maintenance History</h2>
      <img src="{% static 'images/wrench.jpg' %}" alt="A picture of a wrench." />
    </div>
    <h3>Add Service</h3>
    <form action="{% url 'add-service' car.id %}" method="post" class="subsection-content" autocomplete="off">
      {% csrf_token %}
      {{ service_form.as_p }}
      <button type="submit" class="btn submit">Add Service</button>
    </form>
    {% if car.service_set.all.count %}
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Service</th>
        </tr>
      </thead>
      <tbody>
        {% for serv in car.service_set.all %}
        <tr>
          <td>{{serv.date}}</td>
          <td>{{serv.get_sType_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="subsection-content">
      <p>⚠️ {{car.make}} {{car.model}} has not been serviced!</p>
    </div>
    {% endif %}
  </section>

  <section class="toys">
    <div class="subsection-title">
      <h2>Mods</h2>
    </div>

    <h3>{{ car.make }} {{ car.model }}'s Mods</h3>
    <div class="subsection-content">
      {% if car.mods.count %} 
        {% for mod in car.mods.all %}
          <div class="toy-container">
            <div class="color-block"></div>
            <a href="{% url 'mod-detail' mod.id %}">
              <p>{{ mod.name }}</p>
            </a>
            <form action="{% url 'remove-mod' car.id mod.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Remove Mod</button>
            </form>
          </div>
        {% endfor %} 
      {% else %}
        <p class="no-toys">{{car.make}} {{ car.model }} doesn't have any mods!</p>
      {% endif %}
    </div>


    <h3>Available Mods</h3>
    <div class="subsection-content">
      {% if mods.count %} 
        {% for mod in mods.all %}
          <div class="toy-container">
            <div class="color-block"></div>
            <a href="{% url 'mod-detail' mod.id %}">
              <p>{{ mod.name }}</p>
            </a>
            <form action="{% url 'associate-mod' car.id mod.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn submit">Add Mod</button>
            </form>
          </div>
        {% endfor %} 
      {% else %}
        <p class="all-toys">{{car.make}} {{car.model}} already has all the available mods</p>
      {% endif %}
    </div>
  </section>
</div>

{% endblock %}

dealership_app/templates/cars/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/cars/car-index.css' %}" />
{% endblock %}
{% block content %}

<section class="page-header">
    <h1>Your Garage</h1>
</section>

<section class="card-container">
    {% if cars.count %}
    {% for car in cars %}
    <div class="card">
        <a href="{% url 'car-detail' car.id %}">
            <div class="card-content">
                <div class="card-img-container">
                    <img src="{% static 'images/wrench.jpg' %}" alt="{{ car.year }} {{ car.make }} {{car.model }}" />
                </div>
                <h2 class="card-title">{{ car.year }} {{ car.make }} {{car.model }}</h2>
                <p><small>{{ car.description }}</small></p>
            </div>
        </a>
    </div>
    {% endfor %}
    {% else %}
    <h2>No cars added yet.</h2>
    <h2>Head over to the "Add a Car" menu to start tracking your car's maintenance!</h2>
    {% endif %}
</section>

{% endblock %}

dealership_app/templates/dealership_app/car_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Car?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>

<h2>Are you sure you want to delete this {{ car.make }} {{ car.model}}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'car-detail' car.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

dealership_app/templates/dealership_app/car_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}
{% block content %}

<div class="page-header">
    {% if car %}
        <h1>Edit Car</h1>
    {% else %}
        <h1>Add a Car</h1>
    {% endif %}
    
</div>

<form action="" method="post" class="form-container">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

dealership_app/templates/dealership_app/mod_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Mod?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'mod-detail' mod.id %}" class="btn secondary"> Cancel </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

dealership_app/templates/dealership_app/mod_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/mods/mod-detail.css' %}" />
{% endblock %} 
{% block content %}

<div class="card">
  <div class="card-bg"></div>
  <div class="card-content">
    <h2>{{ mod.name }}</h2>
    <p>{{ mod.description }}</p>
  </div>
</div>
{% if user == mod.created_by %}
<a href="{% url 'mod-update' mod.id %}" class="btn warn">Edit</a>
<a href="{% url 'mod-delete' mod.id %}" class="btn danger">Delete</a>
{% endif %}

{% endblock %}

dealership_app/templates/dealership_app/mod_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add Mod</h1>
    {% endif %}

  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

dealership_app/templates/dealership_app/mod_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/mods/mod-index.css' %}" />
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>All Mods</h1>
</section>

<section class="card-container">
  {% for mod in mod_list %}
    <div class="card">
      <div class="card-bg"></div>
      <a href="{% url 'mod-detail' mod.id %}">
        <div class="card-content">
          <h2>{{ mod.name }}</h2>

        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

dealership_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}

{% block content %}

{% if not user.is_authenticated %}
<section>
  <div class = "welcome">
    <h2>Welcome to Garage Keeper!</h2>
    <h2>It looks like you aren't logged in. </h2>
    <h2>Sign up or Login</h2>
  </div>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %} {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>

{% else %}

<section>

  <div class = "welcome">
    <h2>Welcome to Garage Keeper!</h2>
    <h2>It looks like you're already signed in!</h2>
    <h2>Head over to "Add a Car" to start building your garage.</h2>
  </div>
</section>
{% endif %}

{% endblock %}

dealership_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}